### ISSUE TITLE
Add extra ways to format numbers

### ISSUE THREAD

**Issue by Mini51** [TheDevConnor/Zura-v2#30]
Add a way to format strings in the ways below

```zura
// allow user to separate each section with _
have x := 100_000_000_000

// as well as allowing the user to separate each section by ,
have s := 100,000,000,000

**Comment by TheDevConnor** [comment]
So I think i may do the first one. The only problem that i can see is not in the lexer but in the vm when we try and use that logic we need to remove the _ from the number.
